//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Judo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class judoEntities1 : DbContext
    {
        public judoEntities1()
            : base("name=judoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Championat> Championat { get; set; }
        public virtual DbSet<ChampionatConfig> ChampionatConfig { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<participants> participants { get; set; }
        public virtual DbSet<Pravila> Pravila { get; set; }
        public virtual DbSet<Sorevnovanie> Sorevnovanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tatami> Tatami { get; set; }
        public virtual DbSet<UchastChamp> UchastChamp { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
