//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Judo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pravila
    {
        public int id_pravila { get; set; }
        public string Name { get; set; }
        public string Score { get; set; }
        public Nullable<int> id_sorevnovanie { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<double> WaitTime { get; set; }
        public Nullable<int> id_uchast { get; set; }
    
        public virtual Sorevnovanie Sorevnovanie { get; set; }
        public virtual UchastChamp UchastChamp { get; set; }
    }
}
