//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Judo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchastChamp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UchastChamp()
        {
            this.Pravila = new HashSet<Pravila>();
            this.Sorevnovanie = new HashSet<Sorevnovanie>();
            this.Sorevnovanie1 = new HashSet<Sorevnovanie>();
        }
    
        public int id_uchast { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> id_champ { get; set; }
        public Nullable<int> id_participants { get; set; }
    
        public virtual ChampionatConfig ChampionatConfig { get; set; }
        public virtual participants participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pravila> Pravila { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovanie> Sorevnovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovanie> Sorevnovanie1 { get; set; }
    }
}
